### ISSUE TITLE
Update to ``hamster-lib`` (from deprecated ``hamsterlib`` package)

### ISSUE THREAD

**Issue by MarSoft** [elbenfreund/hamster_cli#172]
There are currently 2 different packages in pypi: [hamster-lib](https://pypi.python.org/pypi/hamster-lib) (current version 0.12.0) and [hamsterlib](https://pypi.python.org/pypi/hamsterlib) (current version 0.1.0).
This repo depends on and imports the latter one, which is probably obsolete.
As a result, `tmp_path` cannot be shared between `hamster-cli` and `hamster-gtk` because they use slightly different library paths and object pickled from `hamster-cli` cannot be imported from `hamster-gtk` and so forth.

I think we should update this package to depend on `hamster-lib` and remove obsolete `hamsterlib` from the pypi altogether to avoid such confusion in the future.
I tried to use `hamster-lib` for hamster-cli myself, and for the first look it seems to work well.

**Comment by elbenfreund** [comment]
Thank you for reporting this. Whilst I was aware of that, work on `hamster-gtk`, prevented me from addressing this earlier. `hamster-lib 0.12.0` also provides significantly improved _raw fact_ parsing which improves some open issues.  If there are no major outcry I would like to update this dependency as part of a proper minor release. One of the main reasons is that `hamster-lib` also provides config related helper methods that used to to ship with `hamster-cli`. So this would lend itself to some adjustments as well. So a timeline of 1-3 weeks would be my current guess.
if someone really feels that this should be prioritized please let me know.

btw: thanks for testdriving :)

**Comment by didierm** [comment]
(**hamster-lib 0.12.0 git8bff760 (20160707)** installed)
Running the latest **hamster-cli 0.12.0 git63f3962 (20160425)** yields the following fatal error :

`$ hamster-cli`

`pkg_resources.DistributionNotFound: The 'hamsterlib>=0.1.0' distribution was not found and is required by hamster-cli`

**Comment by elbenfreund** [comment]
I really need to get this out. Sorry for the delay. Its on my desk again.
